### ISSUE TITLE
how do i get all followers?

### ISSUE THREAD

**Issue by guifelix** [InstaPy/instapy-research#2]
I'm trying to get all followers from an account but i'm stuck with a 10000 limit

**Comment by Tkd-Alex** [comment]
@guifelix  how did you get to a thousand? I have serious problems with 429 too many request, rate limit

**Comment by guifelix** [comment]
@Tkd-Alex I didn't try much after that, and by that time (the code version) it just worked.... I didn't tweak the code to work... it just worked. Sorry about not helping much, but this is what happened.

**Comment by scriptworld-git** [comment]
seems to be fixed
